experiment_dir: inference_output
n_forward_steps: 400
forward_steps_in_memory: 50
checkpoint_path: ../../emulator/ace_ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
initial_condition:
  path: ../../emulator/climSST/ic_2021.zarr
  start_indices:
    n_initial_conditions: 2
    first: 0
    interval: 3
  engine: zarr
forcing_loader:
  dataset:
    data_path: ../../emulator/climSST
    file_pattern: forcing_2021.zarr
    engine: zarr
    n_repeats: 2
  num_data_workers: 2
data_writer:
  save_prediction_files: false
  save_monthly_files: false
